#! /bin/sh

### Autostart Applications ###
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x wired > /dev/null || wired &

### Monitor Settings ###

## Define Desktop Names ##
bspc monitor -d " DEV " " WWW " " SYS " " DOC " " CHAT " " MUS " " GFX "

## Monitor Management Settings ##
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true

### Global Settings ###

## Node Borders & Gaps ##
bspc config border_width         3
bspc config window_gap           4

## Scheme Settings ##
bspc config split_ratio                     0.52
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config single_monacle                  false
bspc config automatic_scheme                alternate
bspc config initial_polarity                second_child
bspc config directional_focus_tightness     high
bspc config removal_adjustment              true

## Pointer Settings ##
bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_corner
bspc config pointer_action3                 resize_side
bspc config focus_follows_pointer           true
bspc config pointer_follows_focus           true
bspc config pointer_follows_monitor         true

## Border Colors ##
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#af3a03"

### Window Rules ### 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a freetube desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
